### ISSUE TITLE
chmod 600 /path/to/your_secret

### ISSUE THREAD

**Issue by danyeaw** [recolic/gnome-keyring-yubikey-unlock#8]
A couple of recommendation, and I can submit a PR if this makes sense:

1. Make /path/to/your_secret your $HOME/.gnupg folder. This helps ensure that it has the right permissions as a location along since we are already encrypting/decrypting with gpg
2. `chmod 600 /path/to/your_secret` so that other users can't access it

I thought these changes to the README would help new users who might not know about file permissions.

**Comment by recolic** [comment]
No I don't think it's necessary... The user should know what he is doing, and making a long README even longer would confuse these Linux newbies...

Jan 25, 2022 10:18:22 Dan Yeaw ***@***.***>:

> A couple of recommendation, and I can submit a PR if this makes sense:
> 
1. > Make /path/to/your_secret your $HOME/.gnupg folder. This helps ensure that it has the right permissions as a location along since we are already encrypting/decrypting with gpg
2. > *chmod 600 /path/to/your_secret* so that other users can't access it

**Comment by danyeaw** [comment]
Alright, understand your point of view :+1:
